const {
  Constants: { APIErrors: { MISSING_ACCESS, MISSING_PERMISSIONS, UNKNOWN_CHANNEL, UNKNOWN_INTERACTION, UNKNOWN_MESSAGE }},
} = require("discord.js");

module.exports = {
  IGNORE_ERRORS: {
    SEND: [ MISSING_PERMISSIONS, UNKNOWN_CHANNEL ],
    UPDATE: [ UNKNOWN_MESSAGE, UNKNOWN_INTERACTION, MISSING_PERMISSIONS, MISSING_ACCESS ],
    EDIT: [ UNKNOWN_MESSAGE, UNKNOWN_INTERACTION, MISSING_PERMISSIONS, MISSING_ACCESS ],
  }
};